### ISSUE TITLE
可以适配MH5000-82 包含资料

### ISSUE THREAD

**Issue by 498110811** [FUjr/modem_feeds#4]
[MH5000-82M+5G模组linux-android内核USB使用指南.pdf](https://github.com/user-attachments/files/17955536/MH5000-82M%2B5G.linux-android.USB.pdf)

PID VID
![QQ图片20241129150340](https://github.com/user-attachments/assets/94f84c15-c11f-4400-a9d3-381c8eb5badc)
![QQ图片20241129150436](https://github.com/user-attachments/assets/66b99c6a-6aa1-46b9-8cb5-5267c64362ce)

**Comment by 498110811** [comment]
AT手册
[Uploading MH5000-82M+5G模组AT命令手册.pdf…]()

**Comment by FUjr** [comment]
暂时没有设备，短期内也没有时间
