### ISSUE TITLE
速率可读性优化

### ISSUE THREAD

**Issue by RabbitYilia** [FUjr/modem_feeds#9]
`上行链路最大比特率 | 18750
下行链路最大比特率 | 18750
传输速率 | 15160
发送速率| 13660`

luci-app-modem里面速率带单位而且传输速率单位会根据大小以KB/s MB/s 显示，咱们能否也加一下？

**Comment by FUjr** [comment]
你好，欢迎Pr，目前个人工作较忙

Get Outlook for iOS<https://aka.ms/o0ukef>
________________________________
From: Rabbit Yilia ***@***.***>
Sent: Friday, December 13, 2024 3:40:08 PM
To: FUjr/modem_feeds ***@***.***>
Cc: Subscribed ***@***.***>
Subject: [FUjr/modem_feeds] 速率可读性优化 (Issue #9)


上行链路最大比特率 | 18750 下行链路最大比特率 | 18750 传输速率 | 15160 发送速率| 13660

luci-app-modem里面速率带单位而且传输速率单位会根据大小以KB/s MB/s 显示，咱们能否也加一下？

―
